default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: PickUp_development

test:
  <<: *default
  database: PickUp_test

production:
  <<: *default
  database: PickUp_production
  username: PickUp
  password: <%= ENV['PICKUP_DATABASE_PASSWORD'] %>
