default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: CleatUp_development

test:
  <<: *default
  database: CleatUp_test

production:
  <<: *default
  database: CleatUp_production
  username: CleatUp
  password: <%= ENV['CLEATUP_DATABASE_PASSWORD'] %>
