User.create(username: "username1", password: "password1")
User.create(username: "username2", password: "password2")
User.create(username: "username3", password: "password3")

Group.create(organizer_id: 1, title: "Group 1", description: "First Group")
Group.create(organizer_id: 1, title: "Group 2", description: "Second Group")
Group.create(organizer_id: 2, title: "Group 3", description: "Third Group")
Group.create(organizer_id: 2, title: "Group 4", description: "Fourth Group")
Group.create(organizer_id: 2, title: "Group 5", description: "Fifth Group")
Group.create(organizer_id: 3, title: "Group 6", description: "Sixth Group")
Group.create(organizer_id: 3, title: "Group 7", description: "Seventh Group")

Event.create(group_id: 1, title: "Event 1", description: "First Event", date_time: (DateTime.now + 30), location: "First Event Location")
Event.create(group_id: 1, title: "Event 2", description: "Second Event", date_time: (DateTime.now + 5), location: "Second Event Location")
Event.create(group_id: 2, title: "Event 3", description: "Third Event", date_time: (DateTime.now + 10), location: "Third Event Location")
Event.create(group_id: 3, title: "Event 4", description: "Fourth Event", date_time: (DateTime.now + 25), location: "Fourth Event Location")
Event.create(group_id: 4, title: "Event 5", description: "Fifth Event", date_time: (DateTime.now + 20), location: "Fifth Event Location")
Event.create(group_id: 4, title: "Event 6", description: "Sixth Event", date_time: (DateTime.now + 15), location: "Sixth Event Location")
Event.create(group_id: 4, title: "Event 7", description: "Sevent Event", date_time: (DateTime.now + 3), location: "Seventh Event Location")
Event.create(group_id: 4, title: "Event 8", description: "Eigth Event", date_time: (DateTime.now + 14), location: "Eigth Event Location")
Event.create(group_id: 4, title: "Event 9", description: "Ninth Event", date_time: (DateTime.now + 7), location: "Ninth Event Location")
Event.create(group_id: 4, title: "Event 10", description: "Tenth Event", date_time: (DateTime.now + 40), location: "Tenth Event Location")

GroupMembership.create(group_id: 1, member_id: 2)
GroupMembership.create(group_id: 1, member_id: 3)
GroupMembership.create(group_id: 2, member_id: 2)
GroupMembership.create(group_id: 3, member_id: 1)
GroupMembership.create(group_id: 4, member_id: 1)

EventReservation.create(event_id: 1, reserver_id: 2)
EventReservation.create(event_id: 1, reserver_id: 3)
EventReservation.create(event_id: 2, reserver_id: 2)
EventReservation.create(event_id: 2, reserver_id: 3)
EventReservation.create(event_id: 5, reserver_id: 1)
EventReservation.create(event_id: 8, reserver_id: 1)
EventReservation.create(event_id: 10, reserver_id: 1)

Interest.create(topic: "Interest 1")
Interest.create(topic: "Interest 2")
Interest.create(topic: "Interest 3")
Interest.create(topic: "Interest 4")
Interest.create(topic: "Interest 5")

Interesting.create(interest_id: 1, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 2, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 3, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 1, interestable_type: "Group")
Interesting.create(interest_id: 1, interestable_id: 2, interestable_type: "Group")
Interesting.create(interest_id: 2, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 3, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 2, interestable_id: 2, interestable_type: "Group")
Interesting.create(interest_id: 2, interestable_id: 3, interestable_type: "Group")
