User.create(username: "LeBron James", password: "password1")
User.create(username: "Kobe Bryant", password: "password2")
User.create(username: "Tiger Woods", password: "password3")
User.create(username: "Michael Jordan", password: "password4")
User.create(username: "Aaron Rodgers", password: "password5")
User.create(username: "Lionel Messi", password: "password6")

Group.create(organizer_id: 1, title: "NBA Hoopers", description: "We play intense games of basketball all over the country. Only join if you can keep up!")
Group.create(organizer_id: 1, title: "Casual Basketball Players", description: "Just like the title says, we are a group that likes playing casual basketball games. Anybody is welcome!")
Group.create(organizer_id: 2, title: "Bay Area Ballers", description: "We play all sports and welcome all skill levels. Come join us!")
Group.create(organizer_id: 2, title: "Female Golfers", description: "Just a group of gals that like to get out and hit the links! We usually get a round every weekend!")
Group.create(organizer_id: 2, title: "Futbol in the US", description: 'Pick-up soccer games here in the states, because we all know what the real "football" is!')
Group.create(organizer_id: 3, title: "Drinking and Driving", description: "Just a group of guys who like to go out and have a good time on the course.")
Group.create(organizer_id: 3, title: "A little bit of everything", description: "We try to mix it up and play a bunch of sports. Anybody is welcome, but we take the games seriously and enjoy competing.")

Event.create(group_id: 1, title: "Rucker Park Session", description: "Serious pick-up sess at the legendary Rucker Park. A crowd will be there to watch us compete, so bring your game face and be ready to put on a show!", date_time: (DateTime.now + 30), location: "Rucker Park, New York, New York")
Event.create(group_id: 1, title: "US vs World", description: "We are organizing a little matchup to see who produces the better talent, the US or the rest of the World. We might have to mix it up a little bit if the teams don't have even numbers.", date_time: (DateTime.now + 5), location: "Bradley Center, Milwaukee, WI")
Event.create(group_id: 2, title: "Afternoon at Rossi Park", description: "Gonna set up a tournament at Rossi Park for all those interested, you must RSVP ahead of time.", date_time: (DateTime.now + 10), location: "Rossi Park, San Francisco, CA")
Event.create(group_id: 3, title: "Shootaround at Oracle Arena", description: "We have the awesome opportunity to shoot around at the Oracle Arena, the home of the Golden State Warriors! This is a once in a lifetime opporunity, so you better not miss out.", date_time: (DateTime.now + 25), location: "Oracle Arena, Oakland, CA")
Event.create(group_id: 4, title: "18 at Presidio Golf Course", description: "Playing 18 at Presidio which is a beautiful course right in downtown SF.", date_time: (DateTime.now + 20), location: "Presidio Golf Course, San Francisco, CA")
Event.create(group_id: 4, title: "Scramble at Pebble Beach", description: "We have a really great opportunity to play at Pebble Beach. Since the course will be challenging, we will have some fun with it and turn it into a scramble with four to a team.", date_time: (DateTime.now + 15), location: "Pebble Beach Resort, Del Monte Forest, CA")
Event.create(group_id: 5, title: "Pick-up games at Golden Gate Park", description: "We will be playing games at Golden Gate Park all throughout the day. Games will be pretty casual and we will be hanging out and grilling as well.", date_time: (DateTime.now + 3), location: "Golden Gate Park, San Francisco, CA")
Event.create(group_id: 7, title: "Night Baseball", description: "We will be playing a casual game of baseball under the lights at Rossi Park in Inner Richmond.", date_time: (DateTime.now + 14), location: "Rossi Park, San Francisco CA")
Event.create(group_id: 6, title: "Maple Bluff 18", description: "Lets have a good at Maple Bluff. We will be renting carts for our round.", date_time: (DateTime.now + 7), location: "Maple Bluff Country Club, Madison, WI")
Event.create(group_id: 5, title: "World Cup Tournament", description: "Trying to get a big tournament together, hopefully with some pretty serious, competitive teams.", date_time: (DateTime.now + 40), location: "George Washington High School, San Francisco, CA")

GroupMembership.create(group_id: 1, member_id: 2)
GroupMembership.create(group_id: 1, member_id: 3)
GroupMembership.create(group_id: 2, member_id: 2)
GroupMembership.create(group_id: 3, member_id: 1)
GroupMembership.create(group_id: 4, member_id: 1)

EventReservation.create(event_id: 1, reserver_id: 2)
EventReservation.create(event_id: 1, reserver_id: 3)
EventReservation.create(event_id: 2, reserver_id: 2)
EventReservation.create(event_id: 2, reserver_id: 3)
EventReservation.create(event_id: 5, reserver_id: 1)
EventReservation.create(event_id: 8, reserver_id: 1)
EventReservation.create(event_id: 10, reserver_id: 1)

Interest.create(topic: "Basketball")
Interest.create(topic: "Football")
Interest.create(topic: "Soccer")
Interest.create(topic: "Golf")
Interest.create(topic: "Baseball")
Interest.create(topic: "Casual Games")
Interest.create(topic: "Skilled Games")
Interest.create(topic: "Coed")
Interest.create(topic: "Male Only")
Interest.create(topic: "Female Only")

Interesting.create(interest_id: 1, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 2, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 3, interestable_type: "User")
Interesting.create(interest_id: 1, interestable_id: 1, interestable_type: "Group")
Interesting.create(interest_id: 1, interestable_id: 2, interestable_type: "Group")
Interesting.create(interest_id: 2, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 3, interestable_id: 1, interestable_type: "User")
Interesting.create(interest_id: 2, interestable_id: 2, interestable_type: "Group")
Interesting.create(interest_id: 2, interestable_id: 3, interestable_type: "Group")
